services:
  blaze:
    image: "samply/blaze:1.6@sha256:4148d6cc9daf1f7237270878535d176b1e24b8d4092dcf636d42778c3a49dbc8"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      DB_BLOCK_CACHE_SIZE: "2048"
      ENABLE_ADMIN_API: "true"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"

volumes:
  blaze-data:
