services:
  blaze:
    image: "samply/blaze:1.6@sha256:fd002226eb99437b3848133cae2f421622a2650e3a14c0c97418b7b75c005705"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      DB_BLOCK_CACHE_SIZE: "2048"
      ENABLE_ADMIN_API: "true"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"

volumes:
  blaze-data:
